### ISSUE TITLE
1891 Cutting Ribbons 

### ISSUE THREAD

**Issue by Almada2021** [doocs/leetcode#1008]
Hello I started to prepare myself for interviews, and I use codeSignals, LeetCode and other programas to learn. but the solution of the problem 1891 cutting ribbons do not pass all the test, when I tried to submit in my code challenge in  codesignal I thought that is because right variable but I am not sure only pass 26 of 32 test I do not verify.
I suppose it is because the tests put relatively huge numbers greater than 1e5.

**Comment by yanglbme** [comment]
Hi @Almada2021, thanks for your feedback.

We've updated the solution of the problem 1891, please try to submit the new solution in your code challenge in codesignal.

https://github.com/doocs/leetcode/tree/main/solution/1800-1899/1891.Cutting%20Ribbons

**Comment by Almada2021** [comment]
Yeah The code passes all tests now
