### ISSUE TITLE
代码切换UI消失

### ISSUE THREAD

**Issue by mhy-666** [doocs/leetcode#2229]
今天刷题的时候发现大佬改了代码展示的UI界面，现在是多种语言展现在一个页面上，感觉不如原来的页面方便直观，这么改是有什么想法吗，有没有可能改回来原来的UI？谢谢~

**Comment by yanglbme** [comment]
@mhy-666 

我们最近会重构整个项目结构以及 UI 界面，目前是一个中间过渡。

可以期待一下新的界面，到时候依然可以很方便地切换代码块 tab~
