### ISSUE TITLE
LeetCode Wiki 网站分类标签问题

### ISSUE THREAD

**Issue by yanglbme** [doocs/leetcode#2509]
## LeetCode Wiki 主页

https://doocs.github.io/leetcode

## 问题

- [ ] 中文题目，每道题上面的标签，无法正常通过锚点跳转到对应的分类
- [ ] 问题分类页，每个分类下的题目，目前是按照字典序排列，应该按照题目编号从小到大排序

## 解决方案

预计可以通过 mkdocs hooks 机制解决

**Comment by yanglbme** [comment]
![image](https://github.com/doocs/leetcode/assets/21008209/f3fcbe32-0ddf-41e7-81ce-468f3b7f63d7)

![image](https://github.com/doocs/leetcode/assets/21008209/3610c665-77ad-4312-bf8a-39da52fcb167)

**Comment by yanglbme** [comment]
已解决 https://github.com/doocs/leetcode/commit/80772f63facf5d3e869dac70181b8e0b6f440d21

**Comment by deant-digital** [comment]
目前使用 Brave v1.76.81 依然有标签排序问题呢 @yanglbme 

![Image](https://github.com/user-attachments/assets/15f74708-4844-4e3f-8143-35100a263734)

**Comment by yanglbme** [comment]
确实有这个问题，我晚点看看

**Comment by yanglbme** [comment]
已修复 @deant-digital
