### ISSUE TITLE
Incorrect solution - 3164. Find the Number of Good Pairs II

### ISSUE THREAD

**Issue by manoharreddyporeddy** [doocs/leetcode#2997]
Below TS solution fails for below test case. I don't have a solution to fix it yet.

===

https://github.com/doocs/leetcode/blob/main/solution/3100-3199/3164.Find%20the%20Number%20of%20Good%20Pairs%20II/README_EN.md#typescript

![image](https://github.com/doocs/leetcode/assets/8236389/7503fdb9-c222-472e-8155-2baf661267d7)

===

Wrong Answer
338 / 687 testcases passed

Input
nums1 =
[1,2]
nums2 =
[3,2]
k =
2

Output
1

Expected
0

===

**Comment by yanglbme** [comment]
Hello, our TS solution code has passed all the test cases. Could you try it again?


![image](https://github.com/doocs/leetcode/assets/21008209/0f74b186-e8f9-43b0-9d56-05a6d9c23980)
