### ISSUE TITLE
Iterating in array

### ISSUE THREAD

**Issue by turkishjoe** [doocs/leetcode#3136]
As i see, It should be for($i = 0;...) not for($i=1...). You use iterating for all elements on another languages. You also can use forearch($prices ...)

https://github.com/doocs/leetcode/blob/80431c75271ab5ed14b57c893db078bc19fa50ec/solution/0100-0199/0121.Best%20Time%20to%20Buy%20and%20Sell%20Stock/Solution.php#L10

**Comment by yanglbme** [comment]
Hello, the PHP code for question 121 is also acceptable. However, to maintain consistency with the coding style of other programming languages, I will make some adjustments to the code. Thank you very much for your feedback.

**Comment by yanglbme** [comment]
#3137
