### ISSUE TITLE
归并排序，JavaScript版的好像是不稳定的

### ISSUE THREAD

**Issue by Colin3191** [doocs/leetcode#399]
归并排序，JavaScript版的好像是不稳定的

**Comment by Colin3191** [comment]
`function mergeSort(arr) {
    if (arr.length < 2) return arr;
    let mid = Math.ceil(arr.length / 2);
    let arrLeft = mergeSort(arr.splice(0, mid));
    let arrRight = mergeSort(arr.splice(-mid));
    return merge(arrLeft, arrRight);
}

function merge(arr1, arr2) {
    let arr = [];
    while (arr1.length && arr2.length) {
        if (arr1[0] < arr2[0]) {
            arr.push(arr1.shift());
        } else {
            arr.push(arr2.shift());
        }
    }
    return [...arr, ...arr1, ...arr2];

`
这里在arr1和arr2都只有一个元素且它们的值相等的情况下，返回的新数组中它们的顺序是交换了的。

**Comment by yanglbme** [comment]
应该是 `if (arr1[0] <= arr2[0])` 吧

**Comment by yanglbme** [comment]
@Colin3191 已更正，谢谢反馈
