### ISSUE TITLE
Is it possible to provide a PDF format edition?

### ISSUE THREAD

**Issue by asyougo** [doocs/leetcode#447]
Or could you give a guide for generating PDF for myself ? I think it is also useful for many people.

**Comment by A-Rivi** [comment]
metoo

**Comment by MaoLongLong** [comment]
docsify-pdf-converter 不太成熟,我们似乎能通过少量的配置用 gitbook 来生成 pdf,虽然它已经不更新了

[Generating eBooks and PDFs](https://github.com/GitbookIO/gitbook/blob/master/docs/ebook.md)

**Comment by yanglbme** [comment]
nice👍，方便的话帮忙配置一下

**Comment by Kurdo1998** [comment]
Jack you please send me your

**Comment by KimYangOfCat** [comment]
也许可以在 release 中提供生成好的 pdf

**Comment by MaoLongLong** [comment]
上次尝试了一下，可能量太大 gitbook 跑不出来，docsify-pdf-converter 不能处理路径中有空格的文件（部分题目的目录名称），去掉空格后，勉强生成的 pdf 因为 tabs 插件，还只能显示一种语言

**Comment by yanglbme** [comment]
看看要不要统一把空格替换为 `-`，并且去掉 `(` `)` @MaoLongLong

**Comment by MaoLongLong** [comment]
> 看看要不要统一把空格替换为 `-`，并且去掉 `(` `)` @MaoLongLong
> 
> 不过这个改动会很大，基本上是把整个项目目录结构都换了

确实，我再想想，因为可能有的人收藏了题解的链接，相当于原先的链接全失效了
