### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Erica-Iris** [doocs/leetcode#633]
[HERE](https://doocs.github.io/leetcode/#/./basic/sorting/BubbleSort/README)
It should be like this
```Java
    private static void bubbleSort(int[] nums) {
        boolean hasChange = **false**;
        for (int i = 0, n = nums.length; i < n - 1 && hasChange; ++i) {
            hasChange = false;
            for (int j = 0; j < n - i - 1; ++j) {
                if (nums[j] > nums[j + 1]) {
                    swap(nums, j, j + 1);
                    hasChange = true;
                }
            }
        }
    }
```

**Comment by yanglbme** [comment]
Hi @Erica-Iris 

if `hasChange` is false, it will never go into the for loop.

**Comment by Erica-Iris** [comment]
> 



> Hi @Erica-Iris
> 
> if `hasChange` is false, it will never go into the outer for loop.

I'm sorry that I was too anxious and didn't look carefully, which caused trouble to everyone.

**Comment by Abraham-80tut** [comment]
> [HERE](https://doocs.github.io/leetcode/#/./basic/sorting/BubbleSort/README)
> It should be like this
> ```Java
>     private static void bubbleSort(int[] nums) {
>         boolean hasChange = **false**;
>         for (int i = 0, n = nums.length; i < n - 1 && hasChange; ++i) {
>             hasChange = false;
>             for (int j = 0; j < n - i - 1; ++j) {
>                 if (nums[j] > nums[j + 1]) {
>                     swap(nums, j, j + 1);
>                     hasChange = true;
>                 }
>             }
>         }
>     }
> ```
