### ISSUE TITLE
题目链接问题错误

### ISSUE THREAD

**Issue by l1135677068** [doocs/leetcode#722]
二叉搜索树最近公共祖先和二叉树最近公共祖先链接错误

**Comment by YangFong** [comment]
> 二叉搜索树最近公共祖先和二叉树最近公共祖先链接错误

嗨，能告知具体的错误位置在哪里吗，我们方便对其修正，也欢迎提交 PR。

**Comment by yanglbme** [comment]
感谢反馈，已修复 @l1135677068
