### ISSUE TITLE
error

### ISSUE THREAD

**Issue by igeekdong** [doocs/leetcode#819]
网站好像打不开了，免费cdn好像被墙了

**Comment by YangFong** [comment]
有时候会出现该状况，最近我连 [npm](https://www.npmjs.com/) 都无法正常访问。

**Comment by yanglbme** [comment]
https://cdn.jsdelivr.net 这个最近有点问题，详情 https://github.com/jsdelivr/jsdelivr/issues/18397

**Comment by yanglbme** [comment]
先暂时换成 unpkg.com，现在应该能打开了

**Comment by YangFong** [comment]
> 暂时换成unpkg.com，现在应该能先打开了

在我这边，unpkg.com 和 cdn.jsdelivr.net 是一样的表现，加载成功很偶然。以至于我使用上了 unpkg.zhimg.com，也许是我个人的 DNS 设置混乱了。

**Comment by yanglbme** [comment]
unpkg.com 会比较慢，但不会像 cdn.jsdelivr.net一样无法访问

**Comment by yanglbme** [comment]
改为 fastly.jsdelivr.net
