### ISSUE TITLE
stars trend is broken in README

### ISSUE THREAD

**Issue by boojack** [doocs/leetcode#824]
<img width="429" alt="image" src="https://user-images.githubusercontent.com/24653555/174316728-effbea53-573b-48df-ad7c-63e4b3904f84.png">

---

Maybe you can use the chart from star-history:

[![Star History Chart](https://api.star-history.com/svg?repos=doocs/leetcode&type=Date)](https://star-history.com/#doocs/leetcode)

with the following codes:
```markdown
## Star History

[![Star History Chart](https://api.star-history.com/svg?repos=doocs/leetcode&type=Date)](https://star-history.com/#doocs/leetcode)
```

**Comment by yanglbme** [comment]
Thanks for your feedback. It's a alternative for us project.
