### ISSUE TITLE
LeetCode 第5题 Python3 版的解法超时

### ISSUE THREAD

**Issue by ChuckieChen945** [doocs/leetcode#848]
LeetCode 第5题 [5. 最长回文子串](https://leetcode.cn/problems/longest-palindromic-substring) Python3 版的[解法](https://github.com/doocs/leetcode/blob/main/solution/0000-0099/0005.Longest%20Palindromic%20Substring/README_EN.md#python3)原样提交后提示 **Time Limit Exceeded**

**Comment by yanglbme** [comment]
没超时呢，我试了。数据规模 $10^3$，算法时间复杂度 $O(n^2)$，可以通过

![image](https://user-images.githubusercontent.com/21008209/192083685-c6baf5fa-2522-411c-bae3-dc73248d287a.png)

**Comment by yanglbme** [comment]
英文站点应该是新增了测试用例了，导致代码无法通过

**Comment by ChuckieChen945** [comment]
没错，英文站点超时了

**Comment by Ashleykkkb** [comment]
`add`

**Comment by yanglbme** [comment]
新增了空间复杂度 $O(1)$ 的解法，这个解法不会超时了。
