### ISSUE TITLE
为什么readme的目录连接在idea中点不进去啊

### ISSUE THREAD

**Issue by noodlesAI** [doocs/leetcode#875]
为什么readme的目录连接在idea中点不进去啊，要啥插件吗

**Comment by YangFong** [comment]
观察了一下，确实不行。JetBrains 系列对于 MD 中的非远程链接不会相对项目目录进行跳转，而必须以 `./xx` 形式来显式标注。

我有两个方案：

- 使用 VSCode 浏览，它支持该格式的跳转。
- 在线浏览站点。

**Comment by yanglbme** [comment]
本地预览或编辑，推荐使用 VSCode，非常好用。
