### ISSUE TITLE
How often the pool is updated?

### ISSUE THREAD

**Issue by 2748198** [doocs/leetcode#883]

**Comment by yanglbme** [comment]
You mean the leetcode's problem list? @2748198

**Comment by Zeeshan-Anwer** [comment]
I am not getting your question.

**Comment by 2748198** [comment]
> You mean the leetcode's problem list? @2748198

yes , I mean leetcode`s problem list.

**Comment by yanglbme** [comment]
We update it every week and keep in sync with LeetCode US/CN sites.
