### ISSUE TITLE
Issue 剑指 Offer II 050. 向下的路径节点之和 c++ answer

### ISSUE THREAD

**Issue by Allen9012** [doocs/leetcode#899]
C++版本 可能由于增加了测试用例，导致int数据溢出无法通过所有测试用例
runtime error: signed integer overflow: 2147483646 - -3 cannot be represented in type 'int' (solution.cpp)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior prog_joined.cpp:33:34
可以修改成long long类型通过测试用例

**Comment by yanglbme** [comment]
感谢反馈，题解已更新
